### ISSUE TITLE
Remove Spam Hack

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/brokernode#120]
Once we decide Go hooknodes are stable enough, we might no longer need to spam to get faster transactions. We should disable all the hacks we had to speed up transactions.

**Comment by rfornea** [comment]
I am not sure how to associate pull requests with issues.  But this is for this issue:  https://github.com/oysterprotocol/brokernode/pull/123

**Comment by AaronVasquez** [comment]
there's a button if you add the Zenhub chrome extension: https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=en-US

**Comment by rfornea** [comment]
Ah cool, thanks!
