### ISSUE TITLE
Address memory and/or open connection issues on the hooknode

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#154]
We have some connections on the hooknode that aren't getting closed.  We fixed one of them, but there seems to be at least one more.  

We have temporary solutions in place for now, but we should address this in the short to medium term.

Priority: Medium

**Comment by AaronVasquez** [comment]
Issue moved to [oysterprotocol/hooknode #54](https://github.com/oysterprotocol/hooknode/issues/54) via [**ZenHub**](https://www.zenhub.com/)
