### ISSUE TITLE
Revisit payment system--wait for PRL to arrive

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#192]
At the moment we are going to have the brokernode just check that a transaction exists on the ETH blockchain, and that everything about the transaction is correct ("to" address, amount, etc.), and will go ahead and let the user start the upload.  

We may want to revisit this and explicitly have the broker wait until it actually has the money first, especially for very large and expensive uploads.

**Comment by AaronVasquez** [comment]
https://github.com/oysterprotocol/smartcontract/blob/master/OysterPearl.sol#L28 Can we assume the transaction is valid if we just listen to the `Transfer` event?

**Comment by rfornea** [comment]
I'm not entirely sure how those solidity events work.  For that transfer event, do you create a listener by calling that event, passing in the from_address, to_address, and value?  And then the event would only fire if it occurs with the specific params you passed in?  

If that is the case I don't see any reason why we wouldn't just listen to it.  

But if it's just generic transfer events and each event has those params (from, to, value) then we'd just have to check that the params are right.

**Comment by AaronVasquez** [comment]
You create a filter. I think you can filter for specific `from` or `to` events. I know this is possible with the JS web3 client. still have to look into the go version
