### ISSUE TITLE
[Broker][Datamap] Bury PRLs in datamap

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/brokernode#204]
https://docs.google.com/document/d/1HnrgdU-TJrH8XLS0sF13WCGunQUoe-tDllf02Tn_mjY/edit?usp=sharing

>Generate an ETH address for each location where we need to bury PRL.  Send the PRL treasure to that address, invoke the “bury” function on it, and retain the private seed key of that address. 

>While building the data map, we’ll need to bury the PRL.  Say our randomly selected number for Sector 1 was 120,003.  When we get to the 120,003rd hash, instead of putting in data from the file, we will bury the PRL there. 

>Select a random number between 0 and the max length of the hashchain.  Don’t yet know what this will be, but let’s just pretend it is 1000.  Let’s say our randomly selected number is 89.

>Make the sidechain/hashchain of the sha256 hash.  The hashchain is a sequence of sha512 hashes, starting from a sha512 hash of the sha256 hash, and with each sha512 hash being a hash of the previous sha512 hash. 

>When we get to the hash corresponding to the random number we selected (in this case, 89), we will use that sha512 hash as a key to encrypt the private seed key.  Then we will convert this result to trytes.  This result is what we will use as the “message” field for this entry in the datamap.

**Comment by rfornea** [comment]
This is done.  It doesn't generate the ETH addresses, and instead assumes that the addresses (and private keys) have been created and stored in the db in the TreasureIdxMap of upload_sessions table.  It uses the indexes and private keys and buries the PRL in the data map.
