### ISSUE TITLE
[Broker][Datamap] Coordinate with beta about where treasure will be buried

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/brokernode#205]
Alpha and beta brokers need to coordinate where treasure will be buried before burying PRLs into the datamap. This will guarantee just 1 treasure per sector, and allow them to work together on the same sector.

1. Before creating an upload session, generate a mapping from sector to index (or random string/seed). include this in the request to beta
   1.  `{ 0:  123, 1: 829, 2: 38, ... }`
2. Beta responds with its own mapping from sector to index.
3. Both alpha and beta will do `hashFunc(idxAlpha, idxBeta) % sectorSize` to determine the index to embed treasure
   1. This will mitigate the possibility of either broker manipulating where to bury treasure
   2. We should use a one-way hash function
4. Do we need to store the treasure indices in the DB?

**Comment by AaronVasquez** [comment]
@pzhao5 Do you think you can handle this?

**Comment by pzhao5** [comment]
How big is the sector? Is every 1KB?

If i have 2MB file size, so it would be 2000 locations for PRL?

Furthermore, Is the index as in term of byte or other Unit.

**Comment by AaronVasquez** [comment]
1. A sector will be 1,000,000 chunks and each chunk is 1kb, so each sector is 1GB. We can hardcode this for now to a smaller number so it's easier to test.

2. 2MB file would be 1 sector

3. Index is a `unit`

**Comment by pzhao5** [comment]
A Unit mean 1KB (or one storage space on Tangle)?
So in 2MB case, it would divide into 2000 Tangles and plus 1 tangle for
pearl. is that correct?

What if file is less than 1KB. How to handle pearl in this case? Still use
2 Tangles? 1 for Pearl, and other one for storing the file (even though it
does not fill all the space)?

**Comment by AaronVasquez** [comment]
We split up a file into chunks. Each chunk is then attached to the tangle.

In the 2mb case, it would split it into 2000 chunks + 1 for PRL, so 2001 chunks in total. These chunks have a sequence in order to rebuild the file, which is why they have an index. The index denotes its place in the sequence.

Your task is to pick a random number between 0 and 2001, which will be the index of the PRL chunk in the sequence of chunks.
