### ISSUE TITLE
[Broker] Better rand support

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/brokernode#217]
>AaronVasquez 7 hours ago  Member
>This is only pseudo random, we should seed it. Probably with a hashed timestamp:
>
>https://golang.org/pkg/hash/
>
```go 
 rand.Seed(hash(time.Now().UTC().UnixNano()))
```

>rfornea 7 hours ago  •  Member
>I am not sure but I believe that seeding could be added in main.go, and would be applicable throughout the application. We use random stuff in several places so this would be nice.

>pzhao5 26 minutes ago  Member
>Agree, let me look into that. Mind filing an issue for that?

**Comment by AaronVasquez** [comment]
@pzhao5 Do you have capacity to take this when you finish your other PR?

**Comment by pzhao5** [comment]
See here:
https://github.com/oysterprotocol/brokernode/pull/243
