### ISSUE TITLE
Implement bulk inserts for datamap creation.

### ISSUE THREAD

**Issue by automyr** [oysterprotocol/brokernode#248]
Right now, when the Broker generates the datamap for the upload session, it populates the database (mariadb) using one INSERT operation for each iteration of the loop (essentially doing only one row per SQL operation)

This is really inefficient and we should implement some kind of bulk insert method if we want the system to be scalable.

The relevant code is mostly here (there may be one or two other functions we need to change): https://github.com/oysterprotocol/brokernode/blob/master/models/data_maps.go#L100-L123

The basic idea I had was to use `db.RawQuery` and just pass along a multi-row INSERT operation: `INSERT INTO table_name VALUES (val1, val2, "row 1"), (val1, val2, "row 2")`. But we could also explore other methods.

**Comment by pzhao5** [comment]
https://github.com/oysterprotocol/brokernode/pull/249
