### ISSUE TITLE
[Brokernode] Do some kind of hashing so that the brokernodes can agree on the treasure indexes.

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#288]
This is in utils.go MergeIndexes method.  

Alpha and Beta must agree to use the same indexes for treasures, per sector.  Currently we're just averaging them but that isn't ideal because it's somewhat predictable--treasures will usually wind up towards the middle of the sector.  

We need to come up with a way for the brokers to agree on the indexes that is:
-deterministic - the same inputs should always result in the same output
-within the bounds of the specified sector
-unpredictable based on the indexes being fed in
-result should never be chunk_idx 0

**Comment by rfornea** [comment]
@pzhao5   This one isn't really urgent, but we'll have to do it at some point.

**Comment by AaronVasquez** [comment]
Is this done?

**Comment by rfornea** [comment]
No

**Comment by nepeckman** [comment]
Current approach to solving this problem:
Seed the random function with the average of the two numbers. Use `rand.Intn` to get a random int between 0 and 1,000,000. This number is reproducible because we seed the random function, it'll be the same as long as a + b is the same. We can then reseed the random function with the current date. This approach hits the requirements of being deterministic and uniformly distributed, but I'd like some feedback.  [Here's a prototype of the suggested method](https://play.golang.org/p/Ze58aH7ceJs)

**Comment by rfornea** [comment]
So let's say that alpha indexes are:
[56,000,  1,250,000,  2,790,000]
And beta's are:
[345,000,  1,823,000,  2,120,000]

Would you reseed for each iteration with the average of each pair of numbers, or just generate 3 numbers from the first seed, and multiply them by sectorNumber + 1?  Either approach would work I guess, but if we were to go with the latter approach, we could even have alpha and beta stop generating multiple random numbers, and each could just provide a single number.  

Another thing to keep in mind, as I mentioned yesterday, is that we use rand elsewhere.  Re-seeding it when we are finished is necessary as you mentioned, but what would we do in the event that some other process is generating random numbers at the same time?  It seems possible that the other process could wind up getting one of the random numbers intended for this method.  Would be great if there was a way to totally isolate an instance of rand.

**Comment by rfornea** [comment]
Another approach would be maybe we could move rand into some kind of utils function and have a way to lock up usage of it temporarily.  That way if some method needs X numbers it can get those X numbers without any other process using rand at the same time.

**Comment by AaronVasquez** [comment]
Instead of using rand, what about a deterministic hash function, so that `hash(a, b)` will give the new index.

Relying on seeding rand properly and calling it in the right order seems too fragile.

**Comment by nepeckman** [comment]
Yeah, that makes sense. I'll try to find an appropriate hashing function. Thanks for the feedback!

**Comment by nepeckman** [comment]
[Here's my attempt at using md5 to hash a location](https://play.golang.org/p/qCk_3U_v5Fc). If this is an acceptable method of hashing, I can try to implement it tonight.

**Comment by rfornea** [comment]
My only concern would be that md5 has a reputation for being insecure.  However, I'm not sure that that makes any difference, for what we're doing here.  The data we are hashing isn't particularly sensitive so it doesn't really matter if someone could "crack" it--the result of the hash is what is sensitive, and if some malicious actor has already gotten the result somehow, they wouldn't bother trying to crack this to see what the original data was.  And even if they _did_ want to, all they'd get is `x + y`, they wouldn't be able to know what `x` was or what `y` was.  

Can you guys think of any problems with this approach?  @AaronVasquez @automyr

**Comment by automyr** [comment]
Seems fine to me, as you say this operation isn't really that sensitive so we can use md5. We can also use something "safer" like keccak or blake, but honestly I wouldn't bother.
