### ISSUE TITLE
[Brokernode] Add Sentry logging of errors throughout the entire brokernode when there's an error

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#306]
Anytime we have this in the brokernode:
```
if err != nil { 
      //do something  
```

Change to this:
```
if err != nil { 
       raven.CaptureError(err, nil) 
       //continue with what you were doing 
```

This sends errors to Sentry and the #errors channel in Slack, so we can keep track of them better.  Will have to add the raven import to the top of files, which is `"github.com/getsentry/raven-go"`.

We have Sentry keys if you need one.

**Comment by pzhao5** [comment]
I will take a look at this and do some logging.

**Comment by pzhao5** [comment]
https://github.com/oysterprotocol/brokernode/pull/310

**Comment by pzhao5** [comment]
Going to close this for now. Feel free to re-open it
