### ISSUE TITLE
[Brokernode] Can only support FileSizeBytes up to a certain size in DB rows

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#311]
When we use certain values for FileSizeBytes that are apparently too large, we get this error:

`mysql create: Error 1264: Out of range value for column 'file_size_bytes' at row 1`

This isn't urgent and can wait until after mainnet.

**Comment by pzhao5** [comment]
file_size_bytes is int, how big is the file Size that lead to this error?

**Comment by AaronVasquez** [comment]
64bit unsigned would give us a large enough number. If anyone uploads a file bigger than that, it would cause other problems...
