### ISSUE TITLE
[Brokernode] Make methods to convert to and from wei

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#329]
We'll need to be able to convert to and from wei.  For sending the PRL to the treasure addresses, we'll start with a float or Big.Float with the price in PRL, but we need to be able to convert this to wei for the actual transaction.

**Comment by AaronVasquez** [comment]
@pzhao5 `go-ethereum` might have a function to do this? If not, you can just multiply by `10^18`

**Comment by pzhao5** [comment]
Does not seem to have any. Just roll our own

**Comment by pzhao5** [comment]
https://github.com/oysterprotocol/brokernode/pull/332
