### ISSUE TITLE
[Brokernode] Add an additional method for getting balances (need both PRL and ETH)

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#340]
Currently we have a method `checkBalance` which I believe gets the balance of PRL (check on this).  We'll need to be able to get the balance of both ETH and PRL.  

Add an additional method `checkETHbalance` to the eth_gateway.go file, so that we'll have a method for getting the PRL balance and a method for getting the ETH balance.  Optionally change the name of the method that gets the PRL balance to `checkPRLBalance` for clarity.  

Note:  If `checkBalance` currently gets the ETH balance, then the new method should be `checkPRLBalance` and `checkBalance` could be renamed to `checkETHBalance`.

**Comment by pzhao5** [comment]
Dup: https://github.com/oysterprotocol/brokernode/issues/349
