### ISSUE TITLE
[Brokernode] Write a task to delete a session if the user hasn't paid in X amount of time.  

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#341]
Some people might go to the website and act like they're about to upload a file, but never actually pay.  We should not hold onto these sessions forever.  We should delete them after a certain amount of time--store this time in some variable so we can change it.  For now let's say 24 hours.  

Queue this up in the jobs/job_runner.go file and the task will live in the jobs folder.  There's some examples of tasks in that folder that also deal with sessions or data maps that are older than a certain amount of time.

**Comment by pzhao5** [comment]
See here https://github.com/oysterprotocol/brokernode/pull/346

**Comment by pzhao5** [comment]
Completed. Feel free to reopen it if more work requires
