### ISSUE TITLE
[Brokernode] When CheckPRLBalance is added, switch most calls to CheckBalance to CheckPRLBalance instead

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#348]
We're adding a CheckPRLBalance method because CheckBalance get the balance in ETH.  There are quite a few places in the code where we'll need to replace calls to CheckBalance with CheckPRLBalance.  For any functions that deal with gas we will most likely still use CheckBalance.

**Comment by pzhao5** [comment]
https://github.com/oysterprotocol/brokernode/pull/352

Dup: https://github.com/oysterprotocol/brokernode/issues/349
