### ISSUE TITLE
[Brokernode] After mainnet, add all modes to the utils/modes.go file

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#370]
Add all modes to utils/modes.go file with appropriate methods to manually set them, as well as to reset them to the .env file values, so we can change them as needed within the unit tests.

**Comment by AaronVasquez** [comment]
I remember seeing that file. This is done right?

**Comment by rfornea** [comment]
I think when I wrote this issue, I was also thinking of the DISABLE_POW and OYSTER_PAYS modes.

**Comment by rfornea** [comment]
@pzhao5   @AaronVasquez   

Do we need the ability to toggle different modes on and off during unit tests?  I can't remember, but either DISABLE_POW or OYSTER_PAYS being enabled will cause some tests to fail.
