### ISSUE TITLE
[Watchout] Too many connections

### ISSUE THREAD

**Issue by pzhao5** [oysterprotocol/brokernode#374]
Currently, we upgrade to AWS aurora, keep monitor this:

1) Increase the number of connections
2) Check the select * from data_maps and maybe cache it. Look like this table is too big.
3) Increase the time for background jobs. Some jobs would run every min, maybe increase to every half hours.

**Comment by AaronVasquez** [comment]
The query is slow because the `Message` field is large. If we can signal to the DB that this is read-only, it won't need to lock, so other queries wont pile up while it waits for the DB to unlock.

Long term solution is to not store the chunk binary in the SQL DB.

**Comment by pzhao5** [comment]
What Message field, and why it is large?

**Comment by AaronVasquez** [comment]
On the `data_maps` table. It stores the binary data that will eventually be stored on the tangle. Each are about 1KB in size. If we fetch 100s or more, it will add up.

**Comment by pzhao5** [comment]
Did not realize that. 

Yep, avoid fetching that field if possible. Otherwise, we could store it as file point in the db.

**Comment by AaronVasquez** [comment]
Go Buffalo seems to support pooling DB connections, so this error should be not be happening if that is true. We need to investigate this a little more.

**Comment by AaronVasquez** [comment]
Going to close this since our badgerDB change should fix this. We can reopen if it starts to crop up again.
