### ISSUE TITLE
[Brokernode] Store datamap's binary data outside of our SQL DB

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/brokernode#384]
SQL is not really meant to store large blobs of data, so we can ease the load on it by storing this in an external store.

The external store can either be the file system or a persistent key/value DB. Here are the pros for each:

### RocksDB or LevelDB
* Data can be stored contiguously on disk, reducing seek overhead
* Offers compressions features
* Transactional (not sure if we need this)
* Higher level of abstraction (don't have to interact with a raw filesystem, which is different across environments like Windows, Mac, Linux)
* Caching layer

## File System
* Less tooling overhead

**Comment by AaronVasquez** [comment]
After a short discussion on slack, we've decided to use https://github.com/dgraph-io/badger

>Alex Moyano
@AaronVasquez if we're going for key:value db I think we should look into badger. It's what Hercules uses, is written in Go and apparently it's considerably faster than Rocks for  large operations

**Comment by rfornea** [comment]
Are we going to batch these?  I.e. instead of each key/value pair being for a single chunk, will it be a key/value pair where the value is, for example, 100-300 chunks worth of message fields?

**Comment by rfornea** [comment]
If we're going for a latter approach, which I think would be better, it would be nice if it would automatically bundle/batch the chunks based on whatever our BundleSize variable value is.

**Comment by AaronVasquez** [comment]
I think badger supports batched reads (need to double check this), so I think we should leave it up to the caller which chunks to get in a batch rather than forcing a batch to be stored at a specific key.

**Comment by nullpilot** [comment]
I wasn't able to dig up the conversation on the filestorage solution a while ago, but it addressed batching. 

Unless Badger makes it really convenient, we should probably go for it. Especially once we use binary for the upload it makes sense to just stream that whole request body to a file, or badger respectively, and only process it once it's being attached.

For the binary downloads with the IXI module I used a scheme that consisted of a uint16 that contained the length of a chunk, followed by the payload, repeated N times depending on batch size. If we used the same for uploads, we could just add the range of idx to the batch via header or multipart, and then dump the binary payload into the storage provider.

Then when processing, just load a batch, and iterate over it by reading in 2 byte as `length` + `length` bytes as `payload`, convert to trytes and attach, rinse and repeat.

**Comment by AaronVasquez** [comment]
Ok, that makes sense. My only concern is that this would be a relatively big change to how we are doing it now with coordination between broker and webinterface deploys. So I would propose we handle this in 2 steps.

1. Convert existing architecture to use badger and deprecate the `Message` field on the data_maps table. We would then deploy this to stop the `too many connections` error.
2. Once that is in production, we can work on coordinating a more thorough change and more optimizations like what you listed.

**Comment by rfornea** [comment]
A 2-step process sounds good to me, provided Step 1 doesn't take a lot of time.  If it does, might as well just go whole hog.

**Comment by pzhao5** [comment]
BadgerDB code completed. Close this issue for now
