### ISSUE TITLE
Investigate ETH: Not Found Error

### ISSUE THREAD

**Issue by pzhao5** [oysterprotocol/brokernode#415]
https://sentry.io/oyster-pearl/broker/issues/576737457/?query=is:unresolved

Is this an error that we need to take action or not. Otherwise, we should remove logging it.

**Comment by rfornea** [comment]
@Astor Thoughts on this issue?

**Comment by Astor** [comment]
https://github.com/oysterprotocol/brokernode/commit/fabea78b3a4e6fbae812836fb0a01d69de0035fe

**Comment by rfornea** [comment]
@Astor  Is the error still going to make it to Sentry from being called somewhere else?

**Comment by Astor** [comment]
Yes, the method using it, getConfirmationStatus returns an error object and waitForConfirmation has the error capture one level up. So it still reports.

**Comment by Astor** [comment]
We can close this issue as it is completed. Error was removed from the lower level.
