### ISSUE TITLE
[Brokernode] Badger and binary message data implementation and testing

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#428]
Already in progress, just creating an issue for tracking/milestone purposes

**Comment by pzhao5** [comment]
Currently code completed and need more testing

**Comment by AaronVasquez** [comment]
@pzhao5 we are planning to deploy wednesday. Is this ready?

**Comment by pzhao5** [comment]
Yep, it is ready. More testing will be nice.
