### ISSUE TITLE
[Brokernode] Batch update of data maps in actions/upload_sessions.go is not changing the msg_status

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#471]
The batch update is not setting the data_maps to `MsgStatusUploaded` which is causing them to never get picked up by process_unassigned_chunks which causes the upload not to succeed.

**Comment by pzhao5** [comment]
I am going to add more test for it

**Comment by pzhao5** [comment]
https://github.com/oysterprotocol/brokernode/pull/473
