### ISSUE TITLE
[Brokernode] Store binary data in badger instead of the trytes

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#482]
Currently we are storing the tryte data in badger.  We can cut the total amount of storage in half by storing the binary data that comes from webinterface instead.  

- when chunk comes in from webinterface, store it as-is rather than converting to trytes
- everywhere the message field is used in the code, we'll have to convert it to trytes using the `ChunkMessageToTrytesWithStopper` method before it is used.  I.e. before it's attached to the tangle, within the `chunksMatch` method in iota_wrappers, etc.  Generally speaking anywhere `GetMessageFromDataMap` is called, we'd need to call `ChunkMessageToTrytesWithStopper` once we have the message (or could call `ChunkMessageToTrytesWithStopper` within `GetMessageFromDataMap`)
- `CreateTreasurePayload` in data_maps.go may need some changes.  We'll need to convert the byte array to a binary string instead of to trytes.  We still will need to pad the message with random trytes before it gets attached to the tangle.  There's probably more than one way to handle this--we may need to create those random trytes, then convert them to binary data, and append that to the message, so that when `ChunkMessageToTrytesWithStopper` runs later, the tryte padding gets turned into trytes again.  The important thing is to ensure that a message payload created "the old way" could still ultimately be decrypted by the webnode, so the resulting trytes message from any payload created for any given inputs into `CreateTreasurePayload` needs to be the same as it is now.

**Comment by pzhao5** [comment]
This is very tricky to get it right.

Consider the case that we put treasure data into BadgerDB and client need to know when to encode it or not (if it is file data, encode it).

Furthermore, when we migrate from sql message (which is encoded) to badgerDB, we also need to know whether the message is encoded or not. Otherwise, it will lead to double encoding.

**Comment by rfornea** [comment]
I think with the client, it may not be an issue.  When the client downloads, the result will be in trytes.  The client will convert it to bytes, and then attempt to decrypt it.  If the decrypted value starts with the Treasure prefix ("Treasure: ") the client knows it is not part of the file data, so it won't add that chunk to the re-assembled file.  If you're talking about knowing whether to convert it to trytes or leave as binary data for saving to sql, maybe it could check the value of the .env variable that turns badger on and only convert to trytes if it is false?  

Giota has a `toTrytes()` method that will throw an error if something is not a valid tryte string.  So if we don't get the error, it's already trytes and we don't need to do anything.  If we do get the error, we need to turn it into trytes.  Perhaps this is something we could use to know if we need to convert to trytes or not, within the `GetMessageFromDataMap` method?   Eventually, there won't be any sql messages anymore, because all the active data_maps are using the badger db.  All the data will be in badger in the binary string form, so we could remove that checking.  

Or maybe we should just reject new downloads for a short while, while all the active downloads "clear out" and then deploy this change.
