### ISSUE TITLE
[Brokernode] Warning: ColumnsForStructWithAlias is deprecated, and will be removed in a future version. Please use ForStructWithAlias instead.

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#489]
Getting this warning from the broker.

**Comment by pzhao5** [comment]
This does not existed. I saw that warning but I can't repo it. And google search of ForStructWithAlias does not return any result

**Comment by rfornea** [comment]
Ah. It must be one of our dependencies that is using this. Hope they update soon.
