### ISSUE TITLE
[Brokernode] Make the v3 and v2 tests run when we run the unit tests.

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/brokernode#599]
Currently, the method which runs the actions suite tests lives in `/actions/actions_test.go`.  The `v2` and `v3` tests don't currently run.  

We can make a method in v2 and v3 that will run the tests in those suites, but we cannot import the `App` from `/actions/app.go` into v2 and v3 otherwise we will have an import cycle.  So a possible option would be for `v2` and `v3` to each have their own `App` for testing purposes.  Or modify the `actions/app.go` file import the `App`s from both `v2` and `v3` and somehow combine them.

**Comment by pzhao5** [comment]
See https://github.com/oysterprotocol/brokernode/pull/601
