### ISSUE TITLE
Update the latest version for iota lib

### ISSUE THREAD

**Issue by pzhao5** [oysterprotocol/brokernode#631]
We need to update the current iota lib to the latest one.

https://github.com/iotaledger/iota.go
This library has just submitted a merge request and lead to a few new changes. See here:
https://github.com/iotaledger/iota.go/commit/77d57410156f031853103f96fd3299c7594d27fd

Rather than import just "github.com/iotaledger/giota", 
We need to:
All giota.Transaction moves to here and must import this: "github.com/iotaledger/iota.go/transaction"

All giota.Address rename to trinary.Hash and import this: "github.com/iotaledger/iota.go/trinary"
All giota.ToTrytes() will be trinary.NewTrytes()
All giota.ToAddress() will be trinary.NewTrytes()

All giota.GetTransactionsToApproveResponse renamed to api.TransactionsToApprove

Use transaction.AsTransactionObjects() to convert Trytes to Transaction object.

Use FindTransactionsQuery instead FindTransactionsRequest

**Comment by MrRedPandabear** [comment]
@pzhao5 At least Zhao remains cool af.

**Comment by MrRedPandabear** [comment]
@MrRedPandabear Oh well.. didn't mean to do that. Sorry. 😅
